#!/bin/bash -login

#PBS -l walltime=24:00:00
#PBS -l nodes=1:ppn=1
#PBS -l mem=4gb
#PBS -N conservation-singlelarge-pop10
#PBS -t 2090-2099

mkdir /mnt/home/dolsonem/conservation/results/1_patch_900_cells_100_killed-pop10
cd ~/avida/cbuild/work

~/avida/cbuild/work/avida -c ~/avida/cbuild/work/avida.cfg -set RANDOM_SEED ${PBS_ARRAYID} -set DATA_DIR /mnt/home/dolsonem/conservation/results/1_patch_900_cells_100_killed-pop10/${PBS_ARRAYID} -set ENVIRONMENT_FILE /mnt/home/dolsonem/conservation/configs/conservation-singlelarge-environment.cfg -set EVENT_FILE /mnt/home/dolsonem/conservation/configs/conservation-events-experiment-pop10.cfg -set BIRTH_METHOD 11 -set DISPERSAL_RATE 1 -set COPY_MUT_PROB 0.0025