#!/bin/bash -login

#PBS -l walltime=24:00:00
#PBS -l nodes=1:ppn=1
#PBS -l mem=4gb
#PBS -N conservation-singlelarge-pop8
#PBS -t 2070-2079

mkdir /mnt/home/dolsonem/conservation/results/1_patch_900_cells_100_killed-pop8
cd ~/avida/cbuild/work

~/avida/cbuild/work/avida -c ~/avida/cbuild/work/avida.cfg -set RANDOM_SEED ${PBS_ARRAYID} -set DATA_DIR /mnt/home/dolsonem/conservation/results/1_patch_900_cells_100_killed-pop8/${PBS_ARRAYID} -set ENVIRONMENT_FILE /mnt/home/dolsonem/conservation/configs/conservation-singlelarge-environment.cfg -set EVENT_FILE /mnt/home/dolsonem/conservation/configs/conservation-events-experiment-pop8.cfg -set BIRTH_METHOD 11 -set DISPERSAL_RATE 1 -set COPY_MUT_PROB 0.0025