#!/bin/bash -login

#PBS -l walltime=24:00:00
#PBS -l nodes=1:ppn=1
#PBS -l mem=4gb
#PBS -N conservation-36patches-pop2
#PBS -t 2110-2119

mkdir /mnt/home/dolsonem/conservation/results/36_patches_5_cells_100_killed-pop2
cd ~/avida/cbuild/work

~/avida/cbuild/work/avida -c ~/avida/cbuild/work/avida.cfg -set RANDOM_SEED ${PBS_ARRAYID} -set DATA_DIR /mnt/home/dolsonem/conservation/results/36_patches_5_cells_100_killed-pop2/${PBS_ARRAYID} -set ENVIRONMENT_FILE /mnt/home/dolsonem/conservation/configs/conservation-36patches_5each-environment.cfg -set EVENT_FILE /mnt/home/dolsonem/conservation/configs/conservation-events-experiment-pop2.cfg -set BIRTH_METHOD 11 -set DISPERSAL_RATE 1 -set COPY_MUT_PROB 0.0025