#!/bin/bash -login

#PBS -l walltime=24:00:00
#PBS -l nodes=1:ppn=1
#PBS -l mem=4gb
#PBS -N conservation-900patches-pop7
#PBS -t 2360-2369

mkdir /mnt/home/dolsonem/conservation/results/900_patches_1_cells_100_killed-pop7
cd ~/avida/cbuild/work

~/avida/cbuild/work/avida -c ~/avida/cbuild/work/avida.cfg -set RANDOM_SEED ${PBS_ARRAYID} -set DATA_DIR /mnt/home/dolsonem/conservation/results/900_patches_1_cells_100_killed-pop7/${PBS_ARRAYID} -set ENVIRONMENT_FILE /mnt/home/dolsonem/conservation/configs/conservation-900patches_1each-environment.cfg -set EVENT_FILE /mnt/home/dolsonem/conservation/configs/conservation-events-experiment-pop7.cfg -set BIRTH_METHOD 11 -set DISPERSAL_RATE 1 -set COPY_MUT_PROB 0.0025